#!/bin/sh

while uci -q get 'ucitrack.@gecoosac[-1]' >/dev/null; do
	uci -q delete 'ucitrack.@gecoosac[-1]' || exit 1
done

section="$(uci -q add ucitrack gecoosac)" || exit 1
[ -n "$section" ] || exit 1
uci -q set "ucitrack.${section}.init=gecoosac" || exit 1
uci -q commit ucitrack || exit 1

rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache
exit 0
