#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@gecoosac[-1]
	add ucitrack gecoosac
	set ucitrack.@gecoosac[-1].init=gecoosac
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache
exit 0
